name: Generate Coverage Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Run Tests
        run: |
          go test -covermode=count -coverprofile=coverage.out $(go list ./... | grep -v cmd/scratch)

      - name: Generate Coverage Badge
        run: |
          go tool cover -func=coverage.out | grep total | awk '{print "Coverage: "$3}' > coverage.txt
          mkdir -p coverage-badge
          echo "# Coverage Badge" > coverage-badge/README.md
          echo "\![](badge.svg)" >> coverage-badge/README.md
        shell: bash

      - name: Upload Coverage Badge
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-badge
