name: Go Test, Coverage, and Badge Generation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Set Environment Variables
        run: echo "GO111MODULE=on" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          go mod tidy
          go mod download

      - name: Run Tests and Generate Coverage
        run: |
          go test -covermode=count -coverprofile=coverage.out $(go list ./... | grep -v cmd/scratch)

      - name: Display Coverage Report
        run: |
          go tool cover -func=coverage.out

      - name: Generate Coverage Badge
        id: coverage-badge
        run: |
          # Extract the coverage percentage from the coverage.out file
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          # Convert the percentage to a number for comparison (e.g., 85.2 -> 85)
          COVERAGE_NUMBER=$(echo $COVERAGE | awk '{print int($1)}')

          # Set badge color based on coverage percentage
          if [ "$COVERAGE_NUMBER" -ge 80 ]; then
            COLOR="AAFF00"
          elif [ "$COVERAGE_NUMBER" -ge 60 ]; then
            COLOR="FFC000"
          else
            COLOR="FF4433"
          fi

          echo "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='20'>
            <rect width='70' height='20' fill='#7393B3'/>
            <rect x='70' width='50' height='20' fill='#${COLOR}'/>
            <text x='35' y='14' fill='#fff' font-family='Verdana' font-size='11'>coverage</text>
            <text x='85' y='14' fill='#fff' font-family='Verdana' font-size='11'>${COVERAGE}%</text>
          </svg>" > badge.svg

      - name: Deploy Coverage Badge to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          destination_dir: badges
