name: Generate Coverage Badge

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23

      - name: Run Tests
        run: |
          go test -covermode=count -coverprofile=coverage.out $(go list ./... | grep -v cmd/scratch)

      - name: Generate Coverage Badge
        run: |
          mkdir -p coverage-badge
          echo "# Coverage Badge" > coverage-badge/README.md
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          COVERAGE_NUMBER=$(echo $COVERAGE | awk '{print int($1)}')

          if [ "$COVERAGE_NUMBER" -ge 80 ]; then
            COLOR="brightgreen"
          elif [ "$COVERAGE_NUMBER" -ge 60 ]; then
            COLOR="yellow"
          else
            COLOR="red"
          fi

          mkdir -p coverage-badge
          echo "<svg xmlns='http://www.w3.org/2000/svg' width='120' height='20'>
            <rect width='70' height='20' fill='#555'/>
            <rect x='70' width='50' height='20' fill='#${COLOR}'/>
            <text x='35' y='14' fill='#fff' font-family='Verdana' font-size='11'>coverage</text>
            <text x='85' y='14' fill='#fff' font-family='Verdana' font-size='11'>${COVERAGE}%</text>
          </svg>" > coverage-badge/badge.svg
          shell: bash

      - name: Upload Coverage Badge
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-badge
